// ===========================================================
// MZ TV — Country list (Arabic names + dial codes)
// Arab League countries (22) are flagged arab:true and always
// rendered first; the rest are sorted alphabetically (Arabic
// locale) at render time in the country-picker component.
// ===========================================================

const MZ_COUNTRIES = [
  // ---------- الدول العربية (22) ----------
  { code: 'EG', ar: 'مصر', dial: '+20', arab: true },
  { code: 'SA', ar: 'السعودية', dial: '+966', arab: true },
  { code: 'AE', ar: 'الإمارات', dial: '+971', arab: true },
  { code: 'KW', ar: 'الكويت', dial: '+965', arab: true },
  { code: 'QA', ar: 'قطر', dial: '+974', arab: true },
  { code: 'BH', ar: 'البحرين', dial: '+973', arab: true },
  { code: 'OM', ar: 'عُمان', dial: '+968', arab: true },
  { code: 'YE', ar: 'اليمن', dial: '+967', arab: true },
  { code: 'IQ', ar: 'العراق', dial: '+964', arab: true },
  { code: 'JO', ar: 'الأردن', dial: '+962', arab: true },
  { code: 'SY', ar: 'سوريا', dial: '+963', arab: true },
  { code: 'LB', ar: 'لبنان', dial: '+961', arab: true },
  { code: 'PS', ar: 'فلسطين', dial: '+970', arab: true },
  { code: 'LY', ar: 'ليبيا', dial: '+218', arab: true },
  { code: 'TN', ar: 'تونس', dial: '+216', arab: true },
  { code: 'DZ', ar: 'الجزائر', dial: '+213', arab: true },
  { code: 'MA', ar: 'المغرب', dial: '+212', arab: true },
  { code: 'MR', ar: 'موريتانيا', dial: '+222', arab: true },
  { code: 'SD', ar: 'السودان', dial: '+249', arab: true },
  { code: 'SO', ar: 'الصومال', dial: '+252', arab: true },
  { code: 'DJ', ar: 'جيبوتي', dial: '+253', arab: true },
  { code: 'KM', ar: 'جزر القمر', dial: '+269', arab: true },

  // ---------- باقي دول العالم ----------
  { code: 'AF', ar: 'أفغانستان', dial: '+93' },
  { code: 'AL', ar: 'ألبانيا', dial: '+355' },
  { code: 'AS', ar: 'ساموا الأمريكية', dial: '+1684' },
  { code: 'AD', ar: 'أندورا', dial: '+376' },
  { code: 'AO', ar: 'أنغولا', dial: '+244' },
  { code: 'AG', ar: 'أنتيغوا وباربودا', dial: '+1268' },
  { code: 'AR', ar: 'الأرجنتين', dial: '+54' },
  { code: 'AM', ar: 'أرمينيا', dial: '+374' },
  { code: 'AU', ar: 'أستراليا', dial: '+61' },
  { code: 'AT', ar: 'النمسا', dial: '+43' },
  { code: 'AZ', ar: 'أذربيجان', dial: '+994' },
  { code: 'BS', ar: 'باهاماس', dial: '+1242' },
  { code: 'BD', ar: 'بنغلاديش', dial: '+880' },
  { code: 'BB', ar: 'باربادوس', dial: '+1246' },
  { code: 'BY', ar: 'بيلاروسيا', dial: '+375' },
  { code: 'BE', ar: 'بلجيكا', dial: '+32' },
  { code: 'BZ', ar: 'بليز', dial: '+501' },
  { code: 'BJ', ar: 'بنين', dial: '+229' },
  { code: 'BT', ar: 'بوتان', dial: '+975' },
  { code: 'BO', ar: 'بوليفيا', dial: '+591' },
  { code: 'BA', ar: 'البوسنة والهرسك', dial: '+387' },
  { code: 'BW', ar: 'بوتسوانا', dial: '+267' },
  { code: 'BR', ar: 'البرازيل', dial: '+55' },
  { code: 'BN', ar: 'بروناي', dial: '+673' },
  { code: 'BG', ar: 'بلغاريا', dial: '+359' },
  { code: 'BF', ar: 'بوركينا فاسو', dial: '+226' },
  { code: 'BI', ar: 'بوروندي', dial: '+257' },
  { code: 'CV', ar: 'الرأس الأخضر', dial: '+238' },
  { code: 'KH', ar: 'كمبوديا', dial: '+855' },
  { code: 'CM', ar: 'الكاميرون', dial: '+237' },
  { code: 'CA', ar: 'كندا', dial: '+1' },
  { code: 'CF', ar: 'أفريقيا الوسطى', dial: '+236' },
  { code: 'TD', ar: 'تشاد', dial: '+235' },
  { code: 'CL', ar: 'تشيلي', dial: '+56' },
  { code: 'CN', ar: 'الصين', dial: '+86' },
  { code: 'CO', ar: 'كولومبيا', dial: '+57' },
  { code: 'CG', ar: 'الكونغو برازافيل', dial: '+242' },
  { code: 'CD', ar: 'الكونغو الديمقراطية', dial: '+243' },
  { code: 'CR', ar: 'كوستاريكا', dial: '+506' },
  { code: 'CI', ar: 'ساحل العاج', dial: '+225' },
  { code: 'HR', ar: 'كرواتيا', dial: '+385' },
  { code: 'CU', ar: 'كوبا', dial: '+53' },
  { code: 'CY', ar: 'قبرص', dial: '+357' },
  { code: 'CZ', ar: 'التشيك', dial: '+420' },
  { code: 'DK', ar: 'الدانمارك', dial: '+45' },
  { code: 'DM', ar: 'دومينيكا', dial: '+1767' },
  { code: 'DO', ar: 'جمهورية الدومينيكان', dial: '+1809' },
  { code: 'EC', ar: 'الإكوادور', dial: '+593' },
  { code: 'SV', ar: 'السلفادور', dial: '+503' },
  { code: 'GQ', ar: 'غينيا الاستوائية', dial: '+240' },
  { code: 'ER', ar: 'إريتريا', dial: '+291' },
  { code: 'EE', ar: 'إستونيا', dial: '+372' },
  { code: 'SZ', ar: 'إسواتيني', dial: '+268' },
  { code: 'ET', ar: 'إثيوبيا', dial: '+251' },
  { code: 'FJ', ar: 'فيجي', dial: '+679' },
  { code: 'FI', ar: 'فنلندا', dial: '+358' },
  { code: 'FR', ar: 'فرنسا', dial: '+33' },
  { code: 'GA', ar: 'الغابون', dial: '+241' },
  { code: 'GM', ar: 'غامبيا', dial: '+220' },
  { code: 'GE', ar: 'جورجيا', dial: '+995' },
  { code: 'DE', ar: 'ألمانيا', dial: '+49' },
  { code: 'GH', ar: 'غانا', dial: '+233' },
  { code: 'GR', ar: 'اليونان', dial: '+30' },
  { code: 'GD', ar: 'غرينادا', dial: '+1473' },
  { code: 'GT', ar: 'غواتيمالا', dial: '+502' },
  { code: 'GN', ar: 'غينيا', dial: '+224' },
  { code: 'GW', ar: 'غينيا بيساو', dial: '+245' },
  { code: 'GY', ar: 'غيانا', dial: '+592' },
  { code: 'HT', ar: 'هايتي', dial: '+509' },
  { code: 'HN', ar: 'هندوراس', dial: '+504' },
  { code: 'HK', ar: 'هونغ كونغ', dial: '+852' },
  { code: 'HU', ar: 'المجر', dial: '+36' },
  { code: 'IS', ar: 'آيسلندا', dial: '+354' },
  { code: 'IN', ar: 'الهند', dial: '+91' },
  { code: 'ID', ar: 'إندونيسيا', dial: '+62' },
  { code: 'IR', ar: 'إيران', dial: '+98' },
  { code: 'IE', ar: 'أيرلندا', dial: '+353' },
  { code: 'IL', ar: 'إسرائيل', dial: '+972' },
  { code: 'IT', ar: 'إيطاليا', dial: '+39' },
  { code: 'JM', ar: 'جامايكا', dial: '+1876' },
  { code: 'JP', ar: 'اليابان', dial: '+81' },
  { code: 'KZ', ar: 'كازاخستان', dial: '+7' },
  { code: 'KE', ar: 'كينيا', dial: '+254' },
  { code: 'KI', ar: 'كيريباتي', dial: '+686' },
  { code: 'KP', ar: 'كوريا الشمالية', dial: '+850' },
  { code: 'KR', ar: 'كوريا الجنوبية', dial: '+82' },
  { code: 'XK', ar: 'كوسوفو', dial: '+383' },
  { code: 'KG', ar: 'قيرغيزستان', dial: '+996' },
  { code: 'LA', ar: 'لاوس', dial: '+856' },
  { code: 'LV', ar: 'لاتفيا', dial: '+371' },
  { code: 'LS', ar: 'ليسوتو', dial: '+266' },
  { code: 'LR', ar: 'ليبيريا', dial: '+231' },
  { code: 'LI', ar: 'ليختنشتاين', dial: '+423' },
  { code: 'LT', ar: 'ليتوانيا', dial: '+370' },
  { code: 'LU', ar: 'لوكسمبورغ', dial: '+352' },
  { code: 'MO', ar: 'ماكاو', dial: '+853' },
  { code: 'MG', ar: 'مدغشقر', dial: '+261' },
  { code: 'MW', ar: 'مالاوي', dial: '+265' },
  { code: 'MY', ar: 'ماليزيا', dial: '+60' },
  { code: 'MV', ar: 'جزر المالديف', dial: '+960' },
  { code: 'ML', ar: 'مالي', dial: '+223' },
  { code: 'MT', ar: 'مالطا', dial: '+356' },
  { code: 'MH', ar: 'جزر مارشال', dial: '+692' },
  { code: 'MX', ar: 'المكسيك', dial: '+52' },
  { code: 'FM', ar: 'ميكرونيسيا', dial: '+691' },
  { code: 'MD', ar: 'مولدوفا', dial: '+373' },
  { code: 'MC', ar: 'موناكو', dial: '+377' },
  { code: 'MN', ar: 'منغوليا', dial: '+976' },
  { code: 'ME', ar: 'الجبل الأسود', dial: '+382' },
  { code: 'MZ', ar: 'موزمبيق', dial: '+258' },
  { code: 'MM', ar: 'ميانمار', dial: '+95' },
  { code: 'NA', ar: 'ناميبيا', dial: '+264' },
  { code: 'NR', ar: 'ناورو', dial: '+674' },
  { code: 'NP', ar: 'نيبال', dial: '+977' },
  { code: 'NL', ar: 'هولندا', dial: '+31' },
  { code: 'NZ', ar: 'نيوزيلندا', dial: '+64' },
  { code: 'NI', ar: 'نيكاراغوا', dial: '+505' },
  { code: 'NE', ar: 'النيجر', dial: '+227' },
  { code: 'NG', ar: 'نيجيريا', dial: '+234' },
  { code: 'MK', ar: 'مقدونيا الشمالية', dial: '+389' },
  { code: 'NO', ar: 'النرويج', dial: '+47' },
  { code: 'PK', ar: 'باكستان', dial: '+92' },
  { code: 'PW', ar: 'بالاو', dial: '+680' },
  { code: 'PA', ar: 'بنما', dial: '+507' },
  { code: 'PG', ar: 'بابوا غينيا الجديدة', dial: '+675' },
  { code: 'PY', ar: 'باراغواي', dial: '+595' },
  { code: 'PE', ar: 'بيرو', dial: '+51' },
  { code: 'PH', ar: 'الفلبين', dial: '+63' },
  { code: 'PL', ar: 'بولندا', dial: '+48' },
  { code: 'PT', ar: 'البرتغال', dial: '+351' },
  { code: 'RO', ar: 'رومانيا', dial: '+40' },
  { code: 'RU', ar: 'روسيا', dial: '+7' },
  { code: 'RW', ar: 'رواندا', dial: '+250' },
  { code: 'KN', ar: 'سانت كيتس ونيفيس', dial: '+1869' },
  { code: 'LC', ar: 'سانت لوسيا', dial: '+1758' },
  { code: 'VC', ar: 'سانت فينسنت والغرينادين', dial: '+1784' },
  { code: 'WS', ar: 'ساموا', dial: '+685' },
  { code: 'SM', ar: 'سان مارينو', dial: '+378' },
  { code: 'ST', ar: 'ساو تومي وبرينسيبي', dial: '+239' },
  { code: 'SN', ar: 'السنغال', dial: '+221' },
  { code: 'RS', ar: 'صربيا', dial: '+381' },
  { code: 'SC', ar: 'سيشل', dial: '+248' },
  { code: 'SL', ar: 'سيراليون', dial: '+232' },
  { code: 'SG', ar: 'سنغافورة', dial: '+65' },
  { code: 'SK', ar: 'سلوفاكيا', dial: '+421' },
  { code: 'SI', ar: 'سلوفينيا', dial: '+386' },
  { code: 'SB', ar: 'جزر سليمان', dial: '+677' },
  { code: 'ZA', ar: 'جنوب أفريقيا', dial: '+27' },
  { code: 'SS', ar: 'جنوب السودان', dial: '+211' },
  { code: 'ES', ar: 'إسبانيا', dial: '+34' },
  { code: 'LK', ar: 'سريلانكا', dial: '+94' },
  { code: 'SR', ar: 'سورينام', dial: '+597' },
  { code: 'SE', ar: 'السويد', dial: '+46' },
  { code: 'CH', ar: 'سويسرا', dial: '+41' },
  { code: 'TW', ar: 'تايوان', dial: '+886' },
  { code: 'TJ', ar: 'طاجيكستان', dial: '+992' },
  { code: 'TZ', ar: 'تنزانيا', dial: '+255' },
  { code: 'TH', ar: 'تايلاند', dial: '+66' },
  { code: 'TL', ar: 'تيمور الشرقية', dial: '+670' },
  { code: 'TG', ar: 'توغو', dial: '+228' },
  { code: 'TO', ar: 'تونغا', dial: '+676' },
  { code: 'TT', ar: 'ترينيداد وتوباغو', dial: '+1868' },
  { code: 'TR', ar: 'تركيا', dial: '+90' },
  { code: 'TM', ar: 'تركمانستان', dial: '+993' },
  { code: 'TV', ar: 'توفالو', dial: '+688' },
  { code: 'UG', ar: 'أوغندا', dial: '+256' },
  { code: 'UA', ar: 'أوكرانيا', dial: '+380' },
  { code: 'GB', ar: 'المملكة المتحدة', dial: '+44' },
  { code: 'US', ar: 'الولايات المتحدة', dial: '+1' },
  { code: 'UY', ar: 'أوروغواي', dial: '+598' },
  { code: 'UZ', ar: 'أوزبكستان', dial: '+998' },
  { code: 'VU', ar: 'فانواتو', dial: '+678' },
  { code: 'VA', ar: 'الفاتيكان', dial: '+379' },
  { code: 'VE', ar: 'فنزويلا', dial: '+58' },
  { code: 'VN', ar: 'فيتنام', dial: '+84' },
  { code: 'ZM', ar: 'زامبيا', dial: '+260' },
  { code: 'ZW', ar: 'زيمبابوي', dial: '+263' },
  { code: 'MU', ar: 'موريشيوس', dial: '+230' },
  { code: 'CK', ar: 'جزر كوك', dial: '+682' },
  { code: 'NU', ar: 'نيوي', dial: '+683' },
  { code: 'GL', ar: 'غرينلاند', dial: '+299' },
  { code: 'FO', ar: 'جزر فارو', dial: '+298' },
  { code: 'GI', ar: 'جبل طارق', dial: '+350' },
  { code: 'AI', ar: 'أنغويلا', dial: '+1264' },
  { code: 'BM', ar: 'برمودا', dial: '+1441' },
  { code: 'VG', ar: 'جزر العذراء البريطانية', dial: '+1284' },
  { code: 'KY', ar: 'جزر كايمان', dial: '+1345' },
  { code: 'TC', ar: 'جزر توركس وكايكوس', dial: '+1649' },
  { code: 'PR', ar: 'بورتوريكو', dial: '+1787' },
  { code: 'NC', ar: 'كاليدونيا الجديدة', dial: '+687' },
  { code: 'PF', ar: 'بولينيزيا الفرنسية', dial: '+689' },
  { code: 'RE', ar: 'ريونيون', dial: '+262' },
];

// Sort helper used by the country-picker: Arab countries first
// (kept in the curated order above), then the rest alphabetically
// using Arabic collation.
function mzSortedCountries() {
  const arab = MZ_COUNTRIES.filter(c => c.arab);
  const rest = MZ_COUNTRIES.filter(c => !c.arab)
    .sort((a, b) => a.ar.localeCompare(b.ar, 'ar'));
  return [...arab, ...rest];
}
